-- ============================================
-- CUSTOMER SEGMENTATION & REVENUE ANALYSIS
-- ============================================

-- Project focus:
-- Analyze purchasing behavior, customer value, repeat purchase patterns,
-- revenue distribution, purchase frequency, and data quality
-- in an e-commerce dataset

-- Dataset: ecommerce
-- Columns:
-- event_time, event_type, product_id, category_id,
-- category_code, brand, price, user_id, user_session

-- ============================================
-- 1. Preview purchase data
-- Prompt: What do purchase events look like?
-- Why: Validate dataset structure and filtering
-- ============================================

SELECT *
FROM ecommerce
WHERE event_type = 'purchase'
LIMIT 10;

-- ============================================
-- 2. Data quality check
-- Prompt: Are there missing values in the full dataset?
-- Why: Identify data quality limitations before analysis, especially for product/category-level insights.
-- ============================================

SELECT
    COUNT(*) AS total_rows,
    SUM(CASE WHEN user_id IS NULL OR user_id = '' THEN 1 ELSE 0 END) AS missing_user_id,
    SUM(CASE WHEN price IS NULL OR price = '' THEN 1 ELSE 0 END) AS missing_price,
    SUM(CASE WHEN category_code IS NULL OR category_code = '' THEN 1 ELSE 0 END) AS missing_category_code,
    SUM(CASE WHEN brand IS NULL OR brand = '' THEN 1 ELSE 0 END) AS missing_brand
FROM ecommerce;

-- ============================================
-- 3. Purchase data quality check
-- Prompt: Is the purchase data reliable for revenue analysis?
-- Why: Ensure purchase events have valid IDs and prices before calculating revenue and customer value.
-- ============================================

SELECT
    COUNT(*) AS purchase_rows,
    SUM(CASE WHEN user_id IS NULL OR user_id = '' THEN 1 ELSE 0 END) AS missing_user_id,
    SUM(CASE WHEN price IS NULL OR price = '' THEN 1 ELSE 0 END) AS missing_price,
    SUM(CASE WHEN CAST(price AS REAL) <= 0 THEN 1 ELSE 0 END) AS invalid_price
FROM ecommerce
WHERE event_type = 'purchase';

-- ============================================
-- 4. Total purchasing users
-- Prompt: How many users made at least one purchase?
-- Why: Define the active customer base used for segmentation.
-- ============================================

SELECT 
    COUNT(DISTINCT user_id) AS total_purchasing_users
FROM ecommerce
WHERE event_type = 'purchase';

-- ============================================
-- 5. Total revenue
-- Prompt: What is the total revenue generated by purchase events?
-- Why: Establish the main revenue baseline for the project.
-- ============================================

SELECT 
    ROUND(SUM(CAST(price AS REAL)), 2) AS total_revenue
FROM ecommerce
WHERE event_type = 'purchase';

-- ============================================
-- 6. Average purchase value
-- Prompt: What is the average purchase value?
-- Why: Understand the typical transaction size and compare it later with the median.
-- ============================================

SELECT 
    ROUND(AVG(CAST(price AS REAL)), 2) AS avg_purchase_value
FROM ecommerce
WHERE event_type = 'purchase';

-- ============================================
-- 7. Median purchase value
-- Prompt: What is the median purchase value?
-- Why: Compare median vs average purchase value to identify skewness in transaction amounts.
-- ============================================

SELECT 
    ROUND(AVG(price), 2) AS median_purchase_value
FROM (
    SELECT CAST(price AS REAL) AS price
    FROM ecommerce
    WHERE event_type = 'purchase'
    ORDER BY price
    LIMIT 2 - (
        SELECT COUNT(*) 
        FROM ecommerce 
        WHERE event_type = 'purchase'
    ) % 2
    OFFSET (
        SELECT (COUNT(*) - 1) / 2
        FROM ecommerce 
        WHERE event_type = 'purchase'
    )
);

-- ============================================
-- 8. Top users by number of purchases
-- Prompt: Which users make the most purchases?
-- Why: Identify highly active customers and understand purchase frequency concentration.
-- ============================================

SELECT 
    user_id,
    COUNT(*) AS total_purchases
FROM ecommerce
WHERE event_type = 'purchase'
GROUP BY user_id
ORDER BY total_purchases DESC
LIMIT 10;

-- ============================================
-- 9. Top users by total spending
-- Prompt: Which users spend the most?
-- Why: Identify top revenue contributors and compare spending with purchase frequency.
-- ============================================

SELECT 
    user_id,
    ROUND(SUM(CAST(price AS REAL)), 2) AS total_spent
FROM ecommerce
WHERE event_type = 'purchase'
GROUP BY user_id
ORDER BY total_spent DESC
LIMIT 10;

-- ============================================
-- 10. Base customer summary
-- Prompt: What does purchasing user's behavior look like?
-- Why: Create a customer-level table with purchases, toatl spend, average order value, and purchasing dates.
-- ============================================

SELECT
    user_id,
    COUNT(*) AS total_purchases,
    ROUND(SUM(CAST(price AS REAL)), 2) AS total_spent,
    ROUND(AVG(CAST(price AS REAL)), 2) AS avg_order_value,
    MIN(event_time) AS first_purchase,
    MAX(event_time) AS last_purchase
FROM ecommerce
WHERE event_type = 'purchase'
GROUP BY user_id
ORDER BY total_spent DESC;

-- ============================================
-- 11. Customer segmentation by total spending
-- Prompt: How can customers be grouped by total spending?
-- Why: Classify customers into Low, Medium, and High Value segments based on monetary contribution.
--
-- Thresholds:
-- Low Value: <= 100
-- Medium Value: > 100 and <= 300
-- high Value: > 300
-- ============================================

SELECT 
    user_id,
    ROUND(SUM(CAST(price AS REAL)), 2) AS total_spent,
    CASE 
        WHEN SUM(CAST(price AS REAL)) > 300 THEN 'High Value'
        WHEN SUM(CAST(price AS REAL)) > 100 THEN 'Medium Value'
        ELSE 'Low Value'
    END AS customer_segment
FROM ecommerce
WHERE event_type = 'purchase'
GROUP BY user_id
ORDER BY total_spent DESC;

-- ============================================
-- 12. Segment distribution
-- Prompt: How many users are in each customer value segment?
-- Why: Understand customer base composition by value level.
-- ============================================

SELECT 
    customer_segment,
    COUNT(*) AS users
FROM (
    SELECT 
        user_id,
        CASE 
            WHEN SUM(CAST(price AS REAL)) > 300 THEN 'High Value'
            WHEN SUM(CAST(price AS REAL)) > 100 THEN 'Medium Value'
            ELSE 'Low Value'
        END AS customer_segment
    FROM ecommerce
    WHERE event_type = 'purchase'
    GROUP BY user_id
)
GROUP BY customer_segment
ORDER BY users DESC;

-- ============================================
-- 13. Revenue by segment
-- Prompt: How much revenue does each customer value segment generate?
-- Why: Identify which segment contributes the most revenue.
-- ============================================

SELECT 
    customer_segment,
    ROUND(SUM(total_spent), 2) AS segment_revenue
FROM (
    SELECT 
        user_id,
        SUM(CAST(price AS REAL)) AS total_spent,
    	CASE
        	WHEN SUM(CAST(price AS REAL)) > 300 THEN 'High Value'
        	WHEN SUM(CAST(price AS REAL)) > 100 THEN 'Medium Value'
        	ELSE 'Low Value'
   		END AS customer_segment
    FROM ecommerce
    WHERE event_type = 'purchase'
    GROUP BY user_id
)
GROUP BY customer_segment
ORDER BY segment_revenue DESC;   

-- ============================================
-- 14. Average spending per segment
-- Prompt: What is the average customer value whithin each segment ?
-- Why: Compare spending intensity across Low, Medium, and High Value customers.
-- ============================================

SELECT 
	customer_segment,
	COUNT(*) AS users,
	ROUND(AVG(total_spent), 2) AS avg_spent_per_user
FROM (
	SELECT 
		user_id,
		SUM(CAST(price AS REAL)) AS total_spent,
		CASE
			WHEN SUM(CAST(price AS REAL)) > 300 THEN 'High Value'
			WHEN SUM(CAST(price AS REAL)) > 100 THEN 'Medium Value'
			ELSE 'Low Value'
		END AS customer_segment
	FROM ecommerce
	WHERE event_type = 'purchase'
	GROUP BY user_id
)
GROUP BY customer_segment
ORDER BY avg_spent_per_user DESC;

-- ============================================
-- 15. Final customer segmentation summary
-- Prompt: What is the full customer segmentation breakdown?
-- Why: Support the README and insight.md with users, % users, revenue and % revenue by segment.
-- ============================================

WITH user_spending AS (
	SELECT 
		user_id, 
		SUM(CAST(price AS REAL)) AS total_spent
	FROM ecommerce
	WHERE event_type = 'purchase'
	GROUP BY user_id
),
segmented_users AS (
	SELECT
		user_id,
		total_spent,
		CASE
			WHEN total_spent > 300 THEN 'High Value'
			WHEN total_spent > 100 THEN 'Medium Value'
			ELSE 'Low Value'
		END AS customer_segment
	FROM user_spending
)
SELECT
	customer_segment,
	COUNT(*) AS users,
	ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM segmented_users), 2) AS pct_users,
	ROUND(SUM(total_spent), 2) AS revenue,
	ROUND(SUM(total_spent) * 100.0 / (SELECT SUM(total_spent) FROM segmented_users), 2) AS pct_revenue
FROM segmented_users
GROUP BY customer_segment
ORDER BY revenue DESC;

-- ============================================
-- 16. Purchase frequency segmentation
-- Prompt: How often do customers purchase?
-- Why: Group customers by purchase frequency to identify one-time, occasional, and frequent buyers.
-- ============================================

SELECT
	frequency_segment,
    COUNT(*) AS users
FROM (
  SELECT
  	user_id,
  	COUNT(*) AS total_purchases,
  	CASE
  		WHEN COUNT(*) >= 5 THEN 'Frequent'
  		WHEN COUNT(*) >=2 THEN 'Occasional'
  		ELSE 'One-time'
  	END AS frequency_segment
  FROM ecommerce
  WHERE event_type = 'purchase'
  GROUP BY user_id
)
GROUP BY frequency_segment
ORDER BY users DESC;

-- ============================================
-- 17. Revenue by frequency
-- Prompt: Which purchase frequency group generates the most revenue?
-- Why: Understand whether revenue is driven by frequent buyers or occasional customers.
-- ============================================

SELECT 
	frequency_segment, 
	COUNT(*) AS users,
	ROUND(SUM(total_spent), 2) AS revenue
FROM (
	SELECT 
		user_id,
		COUNT(*) AS total_purchases,
		SUM(CAST(price AS REAL)) AS total_spent,
		CASE
			WHEN COUNT(*)>=5 THEN 'Frequent'
			WHEN COUNT(*)>=2 THEN 'Occasional'
			ELSE 'One-time'
		END AS frequency_segment
	FROM ecommerce
	WHERE event_type='purchase'
	GROUP BY user_id
)
GROUP BY frequency_segment
ORDER BY revenue DESC;

-- ============================================
-- 18. Repeat vs one-time customers
-- Prompt: How many customers purchased once vs multiple times?
-- Why: Measure repeat behavior and retention potential.
-- ============================================

SELECT 
	customer_type, 
	COUNT(*) AS users
FROM (
	SELECT 
		user_id,
		COUNT(*) AS total_purchases,
		CASE 
			WHEN COUNT(*) = 1 THEN 'One-time' 
			ELSE 'Repeat' 
		END AS customer_type
	FROM ecommerce
	WHERE event_type = 'purchase'
	GROUP BY user_id
)
GROUP BY customer_type
ORDER BY users DESC;

-- ============================================
-- 19. Revenue by repeat vs one-time customers
-- Prompt: How much revenue comes from repeat customers vs one-time customers?
-- Why: Identify whether retention drives revenue more than single purchases.
-- ============================================

SELECT 
		customer_type, 
		ROUND(SUM(total_spent), 2) AS revenue
FROM (
	SELECT 
		user_id,
		COUNT(*) AS total_purchases,
		SUM(CAST(price AS REAL)) AS total_spent,
		CASE 
			WHEN COUNT(*) = 1 THEN 'One-time' 
			ELSE 'Repeat' 
		END AS customer_type
	FROM ecommerce
	WHERE event_type = 'purchase'
	GROUP BY user_id
)
GROUP BY customer_type
ORDER BY revenue DESC;

-- ============================================
-- 20. Final repeat vs one-time summary
-- Prompt: What is the complete repeat vs one-time customer breakdown ?
-- Why: Support README and insights.md with user count, % users, revenue, and % revenue by customer type.
-- ============================================

WITH customer_purchase_summary AS (
	SELECT 
		user_id,
		COUNT(*) AS total_purchases,
		SUM(CAST(price AS REAL)) AS total_spent
	FROM ecommerce
	WHERE event_type = 'purchase'
	GROUP BY user_id
),
customer_type_summary AS (
	SELECT
		CASE 
			WHEN total_purchases = 1 THEN 'One-time' 
			ELSE 'Repeat' 
		END AS customer_type,
		COUNT(*) AS users,
		SUM(total_spent) AS revenue
	FROM customer_purchase_summary
	GROUP BY customer_type
)
SELECT
	customer_type,
	users,
	ROUND(users * 100.0 / (SELECT SUM(users) FROM customer_type_summary), 2) AS pct_users,
	ROUND(revenue, 2) AS revenue,
	ROUND(revenue * 100.0 / (SELECT SUM(revenue) FROM customer_type_summary), 2) AS pct_revenue
FROM customer_type_summary
ORDER BY revenue DESC;

-- ============================================
-- 21. Recency analysis
-- Prompt: When was each customer's most recent purchase?
-- Why: Identify recently active customers and support retention analysis.
-- ============================================

SELECT 
		user_id, 
		MAX(event_time) AS last_purchase_date
FROM ecommerce
WHERE event_type = 'purchase'
GROUP BY user_id
ORDER BY last_purchase_date DESC;

-- ============================================
-- 22. First vs last purchase date
-- Pompt: What is the first and last purchase date for each customer?
-- Why: Measure customer engagement over time and identify repeat behavior patterns.
-- ============================================

SELECT 
	user_id,
	MIN(event_time) AS first_purchase_date,
	MAX(event_time) AS last_purchase_date,
	COUNT(*) AS total_purchases,
	ROUND(SUM(CAST(price AS REAL)), 2) AS total_spent
FROM ecommerce
WHERE event_type = 'purchase'
GROUP BY user_id
ORDER BY total_purchases DESC, total_spent DESC;

-- ============================================
-- 23. Value + frequency combined segmentation
-- Prompt: How do customer value and purchase frequency combine at the user level?
-- Why: Build a more strategic customer profile that combines total spending and number of purchases.
-- ============================================

SELECT 
	user_id,
	ROUND(SUM(CAST(price AS REAL)), 2) AS total_spent,
	COUNT(*) AS total_purchases,
	CASE
		WHEN SUM(CAST(price AS REAL)) > 300 AND COUNT(*) >= 2 THEN 'High Value Loyal'
		WHEN SUM(CAST(price AS REAL)) > 300 AND COUNT(*) = 1 THEN 'High Value One-Time'
		WHEN SUM(CAST(price AS REAL)) > 100 AND COUNT(*) >= 2 THEN 'Medium Value Repeat'
		WHEN SUM(CAST(price AS REAL)) > 100 AND COUNT(*) = 1 THEN 'Medium Value One-Time'
		ELSE 'Low Value'
	END AS customer_profile
FROM ecommerce
WHERE event_type = 'purchase'
GROUP BY user_id
ORDER BY total_spent DESC, total_purchases DESC;

-- ============================================
-- 24. Distribution of combined customer profiles
-- Prompt: How many customers belong to each value-frequency profile?
-- Why: Understand the distribution of strategic customer profiles.
-- ============================================

SELECT 
	customer_profile,
	COUNT(*) AS users
FROM (
	SELECT
		user_id,
		SUM(CAST(price AS REAL)) AS total_spent,
		COUNT(*) AS total_purchases,
		CASE
			WHEN SUM(CAST(price AS REAL)) > 300 AND COUNT(*) >= 2 THEN 'High Value Loyal'
			WHEN SUM(CAST(price AS REAL)) > 300 AND COUNT(*) = 1 THEN 'High Value One-Time'
			WHEN SUM(CAST(price AS REAL)) > 100 AND COUNT(*) >= 2 THEN 'Medium Value Repeat'
			WHEN SUM(CAST(price AS REAL)) > 100 AND COUNT(*) = 1 THEN 'Medium Value One-Time'
			ELSE 'Low Value'
		END AS customer_profile
	FROM ecommerce 
	WHERE event_type = 'purchase'
	GROUP BY user_id
)
GROUP BY customer_profile
ORDER BY users DESC;

-- ============================================
-- 25. Revenue by combined customer profiles
-- Prompt: How much revenue does each value-frequency profile generate?
-- Why: Identify which combined customer profiles contribute the most revenue.
-- ============================================

SELECT 
	customer_profile,
	ROUND(SUM(total_spent), 2) AS revenue
FROM (
	SELECT
		user_id,
		SUM(CAST(price AS REAL)) AS total_spent,
		COUNT(*) AS total_purchases,
		CASE
			WHEN SUM(CAST(price AS REAL)) > 300 AND COUNT(*) >= 2 THEN 'High Value Loyal'
			WHEN SUM(CAST(price AS REAL)) > 300 AND COUNT(*) = 1 THEN 'High Value One-Time'
			WHEN SUM(CAST(price AS REAL)) > 100 AND COUNT(*) >= 2 THEN 'Medium Value Repeat'
			WHEN SUM(CAST(price AS REAL)) > 100 AND COUNT(*) = 1 THEN 'Medium Value One-Time'
			ELSE 'Low Value'
		END AS customer_profile
	FROM ecommerce 
	WHERE event_type = 'purchase'
	GROUP BY user_id
)
GROUP BY customer_profile
ORDER BY revenue DESC;

-- ============================================
-- 26. Final combined profile summary
-- Prompt: What is the final breakdown of combined customer profiles?
-- Why: Support the strategic segmentation with users, % users, revenue, and % revenue.
-- ============================================

WITH customer_profiles AS (
	SELECT
		user_id,
		SUM(CAST(price AS REAL)) AS total_spent,
		COUNT(*) AS total_purchases,
		CASE
			WHEN SUM(CAST(price AS REAL)) > 300 AND COUNT(*) >= 2 THEN 'High Value Loyal'
			WHEN SUM(CAST(price AS REAL)) > 300 AND COUNT(*) = 1 THEN 'High Value One-Time'
			WHEN SUM(CAST(price AS REAL)) > 100 AND COUNT(*) >= 2 THEN 'Medium Value Repeat'
			WHEN SUM(CAST(price AS REAL)) > 100 AND COUNT(*) = 1 THEN 'Medium Value One-Time'
			ELSE 'Low Value'
		END AS customer_profile
	FROM ecommerce 
	WHERE event_type = 'purchase'
	GROUP BY user_id
)
SELECT
	customer_profile,
	COUNT(*) AS users,
	ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM customer_profiles), 2) AS pct_users,
	ROUND(SUM(total_spent), 2) AS revenue,
	ROUND(SUM(total_spent) * 100.0 / (SELECT SUM(total_spent) FROM customer_profiles), 2) AS pct_revenue
FROM customer_profiles
GROUP BY customer_profile
ORDER BY revenue DESC;

-- ============================================
-- 27. Revenue concentration: Top 10 customers
-- Prompt: How much revenue comes from the top 10 customers?
-- Why: Evaluate whether revenue depends on a small group of high-value users.
-- ============================================

WITH user_revenue AS (
	SELECT
		user_id,
		SUM(CAST(price AS REAL)) AS total_spent
	FROM ecommerce
	WHERE event_type = 'purchase'
	GROUP user_id
),
top_10 AS (
	SELECT
		user_id,
		total_spent
	FROM user_revenue
	ORDER BY total_spent DESC
	LIMIT 10
)
SELECT
	ROUND(SUM(total_spent), 2) AS top_10_revenue,
	ROUND(
		SUM(total_spent) * 100.0 / (
			SELECT SUM(total_spent) 
			FROM user_revenue
		), 
		2
	) AS top_10_revenue_share_pct
FROM top_10;

-- ============================================
-- 28. Top 10 customer detail
-- Prompt: Who are the top 10 customers by revenue?
-- Why: Identify top customer profiles and compare purchase frequency, total spend, and average purchase value.
-- ============================================

SELECT 
	user_id, 
	COUNT(*) AS total_purchases,
	ROUND(SUM(CAST(price AS REAL)), 2) AS total_spent
	ROUND(AVG(CAST(price AS REAL)), 2) AS avg_purchase_value
	SUM(price)
FROM ecommerce
WHERE event_type = 'purchase'
GROUP BY user_id
ORDER BY total_spent DESC
LIMIT 10 ;

-- ============================================
-- 29. Product-level purchase summary
-- Prompt: Which products generate the most purchases and revenue?
-- Why: Analyze product-level performance when product_id is more reliable than category_code.
-- ============================================

SELECT 
	product_id, 
	COUNT(*) AS purchases,
	ROUND(SUM(CAST(price AS REAL)), 2) AS revenue,
	ROUND(AVG(CAST(price AS REAL)), 2) AS avg_price
FROM ecommerce
WHERE event_type = 'purchase'
GROUP BY product_id
ORDER BY revenue DESC
LIMIT 20;

-- ============================================
-- 30. Brand-level purchase summary
-- Prompt: Which brands generate the most purchases and revenue?
-- Why: Explore brand-level performance while accounting for missing brand values.
-- ============================================

SELECT 
	CASE
		WHEN brand IS NULL OR brand = '' THEN 'Unknown'
		ELSE brand
	END AS brand_clean,
	COUNT(*) AS purchases,
	ROUND(SUM(CAST(price AS REAL)), 2) AS revenue,
	ROUND(AVG(CAST(price AS REAL)), 2) AS avg_price
FROM ecommerce
WHERE event_type = 'purchase'
GROUP BY brand_clean
ORDER BY revenue DESC
LIMIT 20;

-- ============================================
-- 31. Category-level purchase summary
-- Prompt: Which categories generate the most purchases and revenue?
-- Why: Explore category-level performance while accounting for missing category_code values.
-- ============================================

SELECT 
	CAST
		WHEN category_code IS NULL OR category_code = '' THEN 'Unknown'
		ELSE category_code
	END AS category_clean, 
	COUNT(*) AS purchases,
	ROUND(SUM(price(price AS REAL)), 2) AS revenue,
	ROUND(AVG(CAST(price AS REAL)), 2) ASavg_price
FROM ecommerce
WHERE event_type = 'purchase'
GROUP BY category_clean
ORDER BY revenue DESC;

-- ============================================
-- 32. Monthly revenue trend
-- Prompt: How does revenue change over time?
-- Why: Identify monthly revenue patterns and seasonality.
-- ============================================

SELECT 
	SUBSTR(REPLACE(event_time, ' UTC',''), 1, 7,) AS purchase_month,
	COUNT(*) AS purchases,
	ROUND(SUM(CAST(price AS REAL)), 2) AS revenue
FROM ecommerce
WHERE event_type = 'purchase'
GROUP BY purchase_month
ORDER purchase_month;

-- ============================================
-- 33. Monthly purchasing users
-- Prompt: How many purchasing users are active each month?
-- Why: Compare customer activity, purchase volume, and revenue over time.
-- ============================================

SELECT 
	SUBSTR(REPLACE(event_time, ' UTC', ''), 1, 7) AS purchase_month,
	COUNT(DISTINCT user_id) AS purchasing_users,
	COUNT(*) AS purchases,
	ROUND(SUM(CAST(price AS REAL)), 2) AS revenue
FROM ecommerce
WHERE event_type = 'purchase'
GROUP BY purchase_month
ORDER BY purchase_month;

-- ============================================
-- 34. Final executive summary table
-- Prompt: What are the main project KPIs in one table?
-- Why: Provide a concise summary for the README and portfolio presentation.
-- ============================================

SELECT 
	COUNT(DISTINCT user_id) AS total_purchasing_users, 
	COUNT(*) AS total_purchase_events,
	ROUND(SUM(CAST(price AS REAL)), 2) AS total_revenue, 
	ROUND(AVG(CAST(price AS REAL)), 2) AS avg_purchase_value
FROM ecommerce
WHERE event_type = 'purchase';

-- ============================================
-- 35. Purchase value distribution
-- Prompt: How are purchases distributed across price ranges?
-- Why: Explain the difference between average and median purchase value and identify low-ticket vs higher-ticket revenue behavior.
-- ============================================

SELECT
	CASE
		WHEN CAST(price AS REAL) < 2 THEN 'Very Low (< $2)'
		WHEN CAST(price AS REAL) < 5 THEN 'Low ($2-$5)'
		WHEN CAST(price AS REAL) <10 THEN 'Medium ($5-$10)'
		ELSE 'High (> $10)'
	END AS price_bucket,
	COUNT(*) AS purchases,
	ROUND(SUM(CAST(price AS REAL)), 2) AS revenue,
	ROUND(AVG(CAST(price AS REAL)), 2) AS avg_price
FROM ecommerce
WHERE event_type = 'purchase'
GROUP BY price_bucket
ORDER BY revenue DESC;

-- ============================================
-- 36. Customer purchase span
-- Prompt: How long do repeat customers remain active?
-- Why: Measure engagement through first and last purchase dates and support customer lifecycle analysis.
-- ============================================

SELECT 
	user_id,
	MIN(event_time) AS first_purchase_date,
	MAX(event_time) AS last_purchase_date,
	COUNT(*) AS total_purchases,
	ROUND(SUM(CAST(price AS REAL)), 2) AS total_spent
FROM ecommerce
WHERE event_type = 'purchase'
GROUP BY user_id
HAVING COUNT(*) >= 2
ORDER BY total_purchases DESC, total_spent DESC;

-- ============================================
-- END OF ANALYSIS
-- ===========================================================

